"""Add OAuth fields to user

Revision ID: a5b9b36ba9ac
Revises: 20260302_0007
Create Date: 2026-03-02 21:56:03.291443
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b9b36ba9ac'
down_revision: Union[str, Sequence[str], None] = '20260302_0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('picture', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
